name: Deployment
on: push
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Dependencies
      #installs all dependencies of this project
        run: npm ci
        #runs linting script
      - name: Lint
          run: npm run lint
      - name:
          run: npm test
      - name : Build code
          run: npm run build
      - name: Deploy code
          run: echo "Deploying ...."